[tool.poetry]
name = "alba"
version = "0.1.0"
description = ""
authors = ["pablovazquezg <pablovazquezg@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.1.13"
streamlit = "^1.32.2"
pymilvus = "^2.4.0"
milvus-model = "^0.1.0"
pymupdf = "^1.24.0"
ollama = "^0.1.8"
tqdm = "^4.66.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
